#!/usr/bin/env python3
"""Fetch AI-generated tracks for the planted half of the catalog.

The audit is only worth reporting if the answer key is real, so the AI side
of the catalog has to be genuinely machine-generated music with documented
provenance -- not synthesised tones labelled "ai", which would make precision
and recall meaningless.

Source: the SONICS dataset (Rahman et al., ICLR 2025), whose fake_songs are
full-length songs generated by Suno (v2, v3, v3.5) and Udio (v32, v130).
That matters twice over: they are the generators an actual catalog would
contain, and they are the populations HumanStandard attributes against.

    https://huggingface.co/datasets/awsaf49/sonics       CC BY-NC 4.0

The archive is 3.8 GB and we want a dozen songs, so this does not download
it. HuggingFace serves byte ranges, and a ZIP's index lives at the end of the
file, so a small file-like object over HTTP ranges is enough for the stdlib
zipfile module to read the directory and inflate individual members. Nothing
outside the standard library, and about 30 MB on the wire instead of 3.8 GB.

    python3 scripts/fetch_ai_tracks.py --limit 12

Writes audio to data/catalog/ai/ and provenance to data/ai_manifest.csv.
"""

from __future__ import annotations

import argparse
import csv
import io
import sys
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from catalog_audit import net  # noqa: E402

DATASET = "awsaf49/sonics"
LICENSE = "CC BY-NC 4.0"
CITATION = ("SONICS: Synthetic Or Not -- Identifying Counterfeit Songs, "
            "Rahman et al., ICLR 2025")
BASE = "https://huggingface.co/datasets/%s/resolve/main/" % DATASET
PARTS = ["fake_songs/part_%02d.zip" % i for i in range(1, 11)]

USER_AGENT = ("catalog-risk-auditor/0.1 "
              "(+https://github.com/codergirl73/catalog-risk-auditor)")
# Directory blocks are the hot ones; member blocks stream past once.
MAX_CACHED_BLOCKS = 64

AUDIO_EXT = {".mp3", ".wav", ".flac", ".m4a", ".ogg"}


class HTTPRangeFile(io.RawIOBase):
    """A seekable read-only file over HTTP byte ranges.

    zipfile needs seek and read; it does not need the bytes to be local. A
    ZIP's central directory sits at the end of the archive, so zipfile seeks
    there first, reads the index, and then reads only the members asked for.
    Over a range-capable server that turns a 3.8 GB download into a few tens
    of megabytes.
    """

    def __init__(self, url: str, chunk: int = 1 << 20) -> None:
        self.url = url
        self.chunk = chunk
        self._pos = 0
        self._cache: dict = {}
        self.size = self._length()

    def _open(self, headers: dict):
        req = urllib.request.Request(self.url, headers=headers)
        return net.urlopen(req, timeout=90)

    def _length(self) -> int:
        req = urllib.request.Request(
            self.url, headers={"User-Agent": USER_AGENT}, method="HEAD")
        with net.urlopen(req, timeout=60) as resp:
            if resp.headers.get("Accept-Ranges") != "bytes":
                raise RuntimeError("server will not serve byte ranges")
            return int(resp.headers["Content-Length"])

    def _block(self, index: int) -> bytes:
        if index in self._cache:
            return self._cache[index]
        start = index * self.chunk
        end = min(start + self.chunk, self.size) - 1
        if start > end:
            return b""
        with self._open({"User-Agent": USER_AGENT,
                         "Range": "bytes=%d-%d" % (start, end)}) as resp:
            data = resp.read()
        # Keep the cache small; the directory blocks are the hot ones and the
        # member blocks are read once and streamed straight out.
        if len(self._cache) > MAX_CACHED_BLOCKS:
            self._cache.clear()
        self._cache[index] = data
        return data

    # -- file protocol ---------------------------------------------------
    def readable(self) -> bool:
        return True

    def seekable(self) -> bool:
        return True

    def tell(self) -> int:
        return self._pos

    def seek(self, offset: int, whence: int = io.SEEK_SET) -> int:
        if whence == io.SEEK_SET:
            self._pos = offset
        elif whence == io.SEEK_CUR:
            self._pos += offset
        else:
            self._pos = self.size + offset
        self._pos = max(0, min(self.size, self._pos))
        return self._pos

    def read(self, n: int = -1) -> bytes:
        if n is None or n < 0:
            n = self.size - self._pos
        n = min(n, self.size - self._pos)
        if n <= 0:
            return b""
        out = bytearray()
        while len(out) < n:
            idx = self._pos // self.chunk
            off = self._pos % self.chunk
            block = self._block(idx)
            if not block:
                break
            take = block[off:off + (n - len(out))]
            if not take:
                break
            out += take
            self._pos += len(take)
        return bytes(out)

    def readinto(self, b) -> int:
        data = self.read(len(b))
        b[:len(data)] = data
        return len(data)


def pick(names, limit: int, stride: int):
    """Spread the selection across the archive rather than taking a run.

    Members sit in generator order, so the first dozen would all come from one
    model. A stride samples across Suno and Udio versions instead.
    """
    audio = [n for n in names
             if Path(n).suffix.lower() in AUDIO_EXT and not n.endswith("/")]
    audio.sort()
    if not audio:
        return []
    step = max(1, min(stride, len(audio) // max(1, limit)))
    return audio[::step][:limit]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=12,
                    help="how many AI tracks to fetch (default 12)")
    ap.add_argument("--part", type=int, default=1,
                    help="which archive part to read, 1-10 (default 1)")
    ap.add_argument("--stride", type=int, default=97,
                    help="sampling stride across the archive")
    ap.add_argument("--out", default=str(ROOT / "data" / "catalog" / "ai"))
    args = ap.parse_args(argv)

    dest = Path(args.out)
    dest.mkdir(parents=True, exist_ok=True)

    url = BASE + PARTS[max(0, min(9, args.part - 1))]
    print("SONICS %s" % PARTS[args.part - 1])
    print("  %s" % DATASET)
    print("  licence %s" % LICENSE)

    try:
        remote = HTTPRangeFile(url)
        print("  archive %.1f GB -- reading the index only" % (remote.size / 1e9))
        zf = zipfile.ZipFile(remote)
        names = zf.namelist()
    except (urllib.error.URLError, OSError, zipfile.BadZipFile,
            RuntimeError) as exc:
        print("Could not read the archive: %s" % exc, file=sys.stderr)
        return 1

    chosen = pick(names, args.limit, args.stride)
    if not chosen:
        print("No audio members found in %s" % PARTS[args.part - 1],
              file=sys.stderr)
        return 1
    print("  %d members, taking %d\n" % (len(names), len(chosen)))

    written = []
    for i, name in enumerate(chosen, 1):
        safe = "sonics__" + Path(name).name
        safe = "".join(c for c in safe if c.isalnum() or c in "._-")[:110]
        out = dest / safe
        if out.exists() and out.stat().st_size > 0:
            print("  [%2d/%d] have %s" % (i, len(chosen), safe[:58]))
            written.append((safe, name))
            continue
        try:
            with zf.open(name) as src:
                data = src.read()
        except Exception as exc:
            print("  [%2d/%d] failed %s: %s" % (i, len(chosen), name[:40], exc))
            continue
        out.write_bytes(data)
        written.append((safe, name))
        print("  [%2d/%d] %-58s %.1f MB"
              % (i, len(chosen), safe[:58], len(data) / 1e6))

    if not written:
        print("Nothing extracted.", file=sys.stderr)
        return 1

    man = ROOT / "data" / "ai_manifest.csv"
    with man.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=[
            "filename", "source_dataset", "archive_member", "license",
            "citation"])
        w.writeheader()
        for safe, member in written:
            w.writerow({"filename": safe, "source_dataset": DATASET,
                        "archive_member": member, "license": LICENSE,
                        "citation": CITATION})

    print("\n%d AI tracks in %s" % (len(written), dest))
    print("provenance: %s" % man)
    print("\nThese are real generated songs from Suno and Udio, not synthesised")
    print("audio. Cite the dataset and its licence in the submission.")
    print("\nNext: python3 scripts/build_dataset.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
